[[plugins]]
package = "netlify-plugin-bundle-env"
[plugins.inputs]
extensions = ["js", "ts", "mts"]
[[redirects]]
from = "/api/*"
to = "https://calendarium-api.hopoke.workers.dev/api/:splat"
status = 200
force = true
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
